
#====================================
#basic

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/unite.vim'

#[[plugins]] #ファイルのtree表示
#repo = 'scrooloose/nerdtree'

[[plugins]] #ファイルのツリー表示
repo = 'Shougo/vimfiler'

[[plugins]] #vimからgitの使用
repo = 'tpope/vim-fugitive'

[[plugins]] #Unite.vimで最近表示したファイルの表示
repo = 'Shougo/neomru.vim'

[[plugins]] #即時実行
repo = 'thinca/vim-quickrun'

#====================================
#edit

[[plugins]] #行末のスペースの可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] #囲むやつ全般の編集の効率化
repo = 'tpope/vim-surround'

[[plugins]] #インデントの可視化
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] #最強の補完
repo = 'Shougo/neocomplete.vim'

[[plugins]] #HTMLまとめてコメントアウト
repo = 'tomtom/tcomment_vim'

[[plugins]] #ステータスラインの表示強化
repo = 'itchyny/lightline.vim'

#[[plugins]] #ステータスラインの表示強化
#repo = 'vim-airline/vim-airline'

#[[plugins]]
#repo = 'Shougo/neocomplcache.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]] #HTML,CSSの記述の省略による高速化
repo = 'mattn/emmet-vim'

#====================================
#lang

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css-syntax'
on_ft = 'css'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'js'

#====================================
#colorscheme

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'vim-scripts/twilight'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'vim-scripts/Wombat'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-scripts/rdark'

[[plugins]]
repo = 'badwolf'
