export XDG_CONFIG_HOME=$HOME/.config

export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000

export ZPLUG_HOME=~/.zplug

export LSCOLORS="gxfxcxdxabegedabagacad"



# share history with other shell
setopt share_history

# set vim like keybind
bindkey -v

autoload -Uz compinit
compinit

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
# /home/taki/Screenshot/hogedate.pngに保存するように設定．
alias gnome-screenshot="gnome-screenshot -f $HOME/Screenshot/$(date +%Y-%m-%d-%H:%M:%S).png"
alias n=nvim

#cd後自動でls
function chpwd() { ls -v -GF --color=auto }

ZSH_CONFIG_BASE_DIR=$HOME/dotfiles/pkgs/zsh

for i in $( ls $ZSH_CONFIG_BASE_DIR/zsh.conf.d/* )
do
  source $i
#  echo $i
done
