export XDG_CONFIG_HOME=$HOME/.config

export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000

export ZPLUG_HOME=~/.zplug

export LSCOLORS="gxfxcxdxabegedabagacad"

# share history with other shell
setopt share_history

# set vim like keybind
bindkey -v

autoload -Uz compinit
compinit

#cd後自動でls
function chpwd() { ls -v -GF --color=auto }

ZSH_CONFIG_BASE_DIR=$HOME/dotfiles/pkgs/zsh

for i in $( ls $ZSH_CONFIG_BASE_DIR/zsh.conf.d/* )
do
  source $i
done
