
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt extended_history
setopt share_history
setopt append_history
setopt inc_append_history
setopt hist_no_store
setopt hist_reduce_blanks
setopt autocd
setopt correct
setopt list_packed

